export enum ExceptionTypeEnum {
  InternalServerError = 'InternalServerError',
  ValidationError = 'ValidationError',
  DatabaseError = 'DatabaseError',
  Unauthorized = 'Unauthorized',
  Authorized = 'Authorized',
  AccessDenied = 'AccessDenied',
  IncorrectEmailOrPassword = 'IncorrectEmailOrPassword',
  IncorrectEmailOrCode = 'IncorrectEmailOrCode',
  EmailAlreadyUsed = 'EmailAlreadyUsed',
  WalletAlreadyUsed = 'WalletAlreadyUsed',
  KycAlreadyAccepted = 'KycAlreadyAccepted',
  KycBlocked = 'KycBlocked',
  KycNotAccepted = 'KycNotAccepted',
  NotFound = 'NotFound',
  BadRequest = 'BadRequest',
  Conflict = 'Conflict',
  IncorrectFile = 'IncorrectFile',
  FileProcessingFailure = 'FileProcessingFailure'
}
